//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 EHomeDemo.rc 使用
//
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EHOMEDEMO_DIALOG            102
#define IDR_HTML_DLGALARMTIME           103
#define IDR_HTML_DLGFLOWINFO            104
#define IDD_SUB_DLG_XML_CFG             107
#define IDR_MAINFRAME                   128
#define IDD_DLG_OUTPUT                  132
#define IDD_DLG_OUTPUT_CTRL             133
#define IDD_DLG_PLAY_BACK               144
#define IDD_DLG_AUDIO_TALK              145
#define IDD_DLG_COMMON_CFG              146
#define IDD_SUB_DLG_DEVICE_CFG          147
#define IDD_DIALOG_REC_FILE             148
#define IDD_DIALOG_PIC_FILE             150
#define IDD_DLG_LOCAL_LISTEN            153
#define IDR_MENU_ELSE                   153
#define IDD_DIALOG1                     154
#define IDD_PTRACK                      155
#define IDB_BITMAP_CAMERA               156
#define IDB_BITMAP_REC                  158
#define IDD_DLG_XML_CFG                 158
#define IDB_BITMAP_PLAY_ALARM           159
#define IDD_DLG_CHANNEL_INFO            159
#define IDD_SUB_DLG_NETWORK_CFG         160
#define IDD_SUB_DLG_CHANNEL_CFG         161
#define IDB_BITMAP_TREE                 162
#define IDD_SUB_DLG_ALARM_CFG           162
#define IDB_BITMAP_LOGOUT               163
#define IDD_DIALOG_CYCLE_PLAYBACK       163
#define IDD_DLG_ALARM_TIME              167
#define IDD_DLG_ALARM_TREE              169
#define IDD_DLG_LOCAL_CFG               170
#define IDR_MENU1                       171
#define IDR_MENU_CHANNEL                171
#define IDD_DLG_FLOW_INFO               172
#define IDD_DIALOG2                     174
#define IDD_SUB_DLG_PIC_CFG             174
#define IDD_DLG_PT_PROXY                178
#define IDD_DLG_GPS_INFO                179
#define IDD_DLG_ISAPI_PT                180
#define IDD_DLG_IP_SELECT               182
#define IDD_DLG_CMS_ALARM               184
#define IDD_DLG_UPGRADE                 185
#define IDD_DLG_DEV_LOG                 186
#define IDD_DLG_DEV_LOG1                187
#define IDD_DLG_ALARM_HOST_LOG          187
#define IDD_DLG_MOTION_CFG              189
#define IDR_MENU_CONFIG                 192
#define IDD_DLG_MOTION_AREA             193
#define IDD_DLG_TRIGGER                 194
#define IDD_DLG_RECORD_CFG              196
#define IDD_DLG_HID_AREA                198
#define IDD_DLG_PRIVATE_AREA            199
#define IDD_DLG_ISAPI_CFG               200
#define IDD_DLG_UPGRADE_HTTP            201
#define IDD_DLG_WIRELESSINFO_UPLOAD_CFG 202
#define IDB_BITMAP_AUDIO                311
#define IDC_TREE_DEV                    1000
#define IDC_CK_CYCLE_RECORD             1000
#define IDC_STATIC_VERSION              1001
#define IDC_EDT_ANALOGCHAN_NUM          1001
#define IDC_EDT_TOTALCHAN_NUM           1002
#define IDC_EDIT_DEV_ADDR               1002
#define IDC_COMBO_WNDNUM                1003
#define IDC_EDT_DISK_NUM2               1003
#define IDC_EDIT_GATEWAY                1003
#define IDC_EDT_DISK_NUM                1003
#define IDC_STATIC_DEMO_VERSION         1004
#define IDC_EDT_COMMAND                 1004
#define IDC_EDT_VOICECHAN_NUM           1004
#define IDC_EDIT_SDK_PORT               1004
#define IDC_EDT_INPUT_XML               1005
#define IDC_EDT_SERIAL_NO               1005
#define IDC_EDIT_HTTP_PORT              1005
#define IDC_COMBO_ALARMIN_NO            1005
#define IDC_EDT_DEVICE_SERIAL_NO        1005
#define IDC_BTN_PREVIEW                 1006
#define IDC_EDT_OUTPUT_XML              1006
#define IDC_EDT_DEVICE_NAME             1006
#define IDC_COMBO_PTZ_CHAN              1006
#define IDC_EDIT_PPPOE_PWD              1006
#define IDC_BTN_CFG                     1007
#define IDC_EDIT_ALARMIN_NAME           1007
#define IDC_EDT_RS232_NUM               1007
#define IDC_EDIT_MTU_VALUE              1007
#define IDC_BTN_LOCAL_CFG               1008
#define IDC_BTN_XML_BTN                 1008
#define IDC_COMBO_ALARMIN_TYPE          1008
#define IDC_EDT_RS485_NUM               1008
#define IDC_EDIT_MAC_ADDR               1008
#define IDC_BTN_PLAYBACK                1009
#define IDC_EDT_NETPORT_NUM             1009
#define IDC_EDIT_MASK_ADDR              1009
#define IDC_BTN_AUDIO_TALK              1010
#define IDC_COMBO_ALARMOUT_NO           1010
#define IDC_EDT_AUXOUT_NUM              1010
#define IDC_EDIT_PPPOE_ADDR             1010
#define IDC_BTN_OTHER                   1011
#define IDC_EDIT_ALARMOUT_NAME          1011
#define IDC_EDT_AUXOUT_NUM2             1011
#define IDC_EDIT_DEVICE_NO              1011
#define IDC_STATIC_WINNUM               1012
#define IDC_COMBO_ALARMOUT_DELAY        1012
#define IDC_BTN_EXIT                    1013
#define IDC_CHECK_ALARMOUT_STATUS       1013
#define IDC_BTN_ADD_DEV                 1014
#define IDC_STATIC_WND1                 1014
#define IDC_STATIC_DEOCDE               1014
#define IDC_BTN_ADD_DEV2                1015
#define IDC_BTN_DEL_DEV                 1015
#define IDC_EDIT_ALARMOUT_ACTION_DELAY  1015
#define IDC_STATIC_WND2                 1015
#define IDC_BTN_PREVIEW_TEST            1016
#define IDC_STATIC_WND3                 1016
#define IDC_EDIT1                       1016
#define IDC_EDIT_PREVIEW_HANDLE         1016
#define IDC_EDIT_OFFSET                 1016
#define IDC_EDIT_DEVICE_TYPE            1016
#define IDC_EDIT_MULTI_ADDR             1016
#define IDC_EDIT_INTERAL_FRAME_I        1016
#define IDC_EDIT_NO_PRESET              1016
#define IDC_EDIT_TIME_NUM               1016
#define IDC_EDIT_XML_INPUT              1016
#define IDC_EDIT_LOG_PATH               1016
#define IDC_EDIT_CHANNEL_NO             1016
#define IDC_EDT_STREAM_PORT             1016
#define IDC_EDIT_IP_SDK                 1016
#define IDC_EDIT_INTERAL                1016
#define IDC_EDITURL                     1016
#define IDC_EDIT_URL                    1016
#define IDC_EDT_PORT                    1016
#define IDC_EDIT_PORT_TRANSMIT          1016
#define IDC_EDIT_ALARM_CHAN             1016
#define IDC_STATIC_WND4                 1017
#define IDC_BUTTON_STOP_PLAY            1017
#define IDC_EDIT_DDNS1_ADDR             1017
#define IDC_EDIT_INTERAL_FRAME_BP       1017
#define IDC_EDIT_NO_CURISE              1017
#define IDC_EDIT_XML_OUTPUT             1017
#define IDC_EDIT_SMS_IP                 1017
#define IDC_EDIT_PORT_SDK               1017
#define IDC_EDIT_MAXSPEED               1017
#define IDC_EDIT_COND                   1017
#define IDC_EDIT3                       1017
#define IDC_STATIC_SEEK_TYPE            1018
#define IDC_EDIT_DDNS2_ADDR             1018
#define IDC_EDIT_NO_TRACK               1018
#define IDC_EDIT_SMS_PORT               1018
#define IDC_EDIT_IP_HTTP                1018
#define IDC_EDIT_MINSPEED               1018
#define IDC_EDIT_INPUT                  1018
#define IDC_EDIT4                       1018
#define IDC_BTN_PTZ_LEFT                1019
#define IDC_BUTTON2                     1019
#define IDC_BTN_START_PREVIEW           1019
#define IDC_BTN_START_LISTEN            1019
#define IDC_BUTTON_START_PLAY           1019
#define IDC_STATIC_FINDING_PIC_FILE     1019
#define IDC_EDIT_ALARMHOST_ADDR         1019
#define IDC_BTN_REQ_AUDIOTALK           1019
#define IDC_BTN_SET_SECURE_ACCESS       1019
#define IDC_EDIT_PORT_HTTP              1019
#define IDC_BUTTON_XML_CONTROL          1019
#define IDC_EDIT_OUTPUT                 1019
#define IDC_BTN_CLOSE                   1019
#define IDC_BTN_CAP_SET                 1019
#define IDC_BTN_GET_RECORD              1019
#define IDC_BTN_PTZ_DOWN                1020
#define IDC_TAB_PLAYBACK                1020
#define IDC_BTN_STOP_LISTEN             1020
#define IDC_STATIC_OFFSET               1020
#define IDC_EDIT_ALARMINPUT_NUM         1020
#define IDC_EDIT_ALARMHOST_PORT         1020
#define IDC_BUTTON_XML_CONFIG           1020
#define IDC_BTN_GET_CAP                 1020
#define IDC_BTN_SET_RECORD              1020
#define IDC_STATIC_SEEK_TYPE2           1020
#define IDC_BTN_PTZ_UP                  1021
#define IDC_COMBO_PIC_FILE_TYPE         1021
#define IDC_EDIT__FILESPAN              1021
#define IDC_EDIT_TOTALALARMINPUT_NUM    1021
#define IDC_EDIT_IPRESOLVER_PORT        1021
#define IDC_EDIT_AMS_IP                 1021
#define IDC_STATIC_SEEK_TYPE3           1021
#define IDC_BTN_PTZ_RIGHT               1022
#define IDC_COMBO_PIC_DATE_START        1022
#define IDC_STATIC_FILESPAN             1022
#define IDC_EDIT_ALARMOUTPUT_NUM        1022
#define IDC_EDIT_IPRESOLVER_ADDR        1022
#define IDC_EDIT_AMS_PORT               1022
#define IDC_STATIC_SEEK_TYPE4           1022
#define IDC_BTN_ZOOM_IN                 1023
#define IDC_COMBO_PIC_TIME_START        1023
#define IDC_EDIT_TOTALALARMOUTPUT_NUM   1023
#define IDC_EDIT_LOG_PATH4              1023
#define IDC_BUTTON_SAVE                 1023
#define IDC_EDIT5                       1023
#define IDC_BTN_FOCUS_NEAR              1024
#define IDC_COMBO_PIC_DATE_STOP         1024
#define IDC_EDIT_STARTCHAN_NUM          1024
#define IDC_EDIT6                       1024
#define IDC_BTN_IRIS_OPEN               1025
#define IDC_COMBO_PIC_TIME_STOP         1025
#define IDC_EDIT_MAXDIGITAL_NUM         1025
#define IDC_EDIT7                       1025
#define IDC_BTN_ZOOM_OUT                1026
#define IDC_LIST_PIC_FILE               1026
#define IDC_EDIT_SIM_SERIAL_NO          1026
#define IDC_COMBO_LOG_DATE_STOP         1026
#define IDC_EDIT8                       1026
#define IDC_BTN_FOCUS_FAR               1027
#define IDC_BTN_SEARCH_PIC_FILE         1027
#define IDC_EDIT_CELLPHONE_NO           1027
#define IDC_COMBO_LOG_TIME_STOP         1027
#define IDC_EDIT9                       1027
#define IDC_BTN_IRIS_CLOSE              1028
#define IDC_STATIC_FINDING_REC_FILE     1028
#define IDC_EDIT_ZEROCHAN_NUM           1028
#define IDC_LIST_DEV_LOG                1028
#define IDC_EDIT10                      1028
#define IDC_BTN_PTZ_LEFT_DOWN           1029
#define IDC_CMB_VOICETALK_CB_TYPE       1029
#define IDC_EDIT_ZEROCHAN_STARTNUM      1029
#define IDC_EDIT11                      1029
#define IDC_SLIDER_CONTRAST             1030
#define IDC_BTN_START_VOICETALK         1030
#define IDC_COMBO_INTELLIGENT_TYPE      1030
#define IDC_EDIT12                      1030
#define IDC_SLIDER_SATURATION           1031
#define IDC_BTN_STOP_VOICETALK          1031
#define IDC_STATIC_PLAY_WND             1031
#define IDC_BTN_PREVIEW_LISTEN          1031
#define IDC_COMBO_MINOR_SCALE           1031
#define IDC_EDIT13                      1031
#define IDC_SLIDER_HUE                  1032
#define IDC_BTN_START_TRANSMIT          1032
#define IDC_CHECK_PPPOE_ENABLE          1032
#define IDC_BTN_SALVE                   1032
#define IDC_EDIT14                      1032
#define IDC_BTN_PTZ_LEFT_UP             1033
#define IDC_BTN_STOP_VOICETALK2         1033
#define IDC_BTN_STOP_TRANSMIT           1033
#define IDC_COMBO_LISTEN_TYPE           1033
#define IDC_EDIT_GATEWAY_ADDR           1033
#define IDC_EDIT15                      1033
#define IDC_BTN_PTZ_RIGHT_UP            1034
#define IDC_EDIT_PPPOE_USER             1034
#define IDC_EDIT16                      1034
#define IDC_BTN_PTZ_RIGHT_DOWN          1035
#define IDC_COMBO_PORT_NO               1035
#define IDC_EDIT_BRIGHT                 1035
#define IDC_EDIT17                      1035
#define IDC_BTN_LIGHT_ON                1036
#define IDC_IPADDRESS1                  1036
#define IDC_EDIT_CONTRAST               1036
#define IDC_EDIT18                      1036
#define IDC_BTN_LIGHT_OFF               1037
#define IDC_EDIT_PORT                   1037
#define IDC_EDIT_SATURATION             1037
#define IDC_COMBO_ALARM_MONITOR         1037
#define IDC_BTN_WIPER_ON                1038
#define IDC_COMBO1                      1038
#define IDC_COMBO_LINK_TYPE             1038
#define IDC_COMBO_PROTOCOL              1038
#define IDC_CMB_AUDIO_TYPE              1038
#define IDC_CMB_VOICE_CHAN              1038
#define IDC_COMBO_SEEK_TYPE             1038
#define IDC_COMBO_NET_TYPE              1038
#define IDC_EDIT_HUE                    1038
#define IDC_COMBO_USEALARMIN            1038
#define IDC_COMBO_OSD_TYPE              1038
#define IDC_COM_SECURE_ACCESS           1038
#define IDC_COM_CMS_ACCESS_TYPE         1038
#define IDC_COMBO_GPS_INFO              1038
#define IDC_COMBO_CMD_DETAIL            1038
#define IDC_COMBO_CMD_TYPE              1038
#define IDC_COM_IP                      1038
#define IDC_EDIT_USERNAME               1038
#define IDC_COMBO_SENSIVE               1038
#define IDC_COMBO_ALARM_TYPE            1038
#define IDC_COMBO1_DAY                  1038
#define IDC_BTN_WIPER_OFF               1039
#define IDC_CMB_MAJOR_SCALE             1039
#define IDC_COMBO_ALARM_VOICE           1039
#define IDC_COMBO_CMD                   1039
#define IDC_EDIT_PASSWORD               1039
#define IDC_COM_ALARM_TYPE              1039
#define IDC_COMBO_SENSIVE_HIDE          1039
#define IDC_COMBO_ALARM_TYPE2           1039
#define IDC_COMBO1_DAY2                 1039
#define IDC_COMBO_TIME_TYPE             1039
#define IDC_BUTTON1                     1040
#define IDC_BTN_REFRESH                 1040
#define IDC_BTN_MANUALIO_START          1040
#define IDC_BTN_IMAGE_REFRESH           1040
#define IDC_BUTTON_START_CYCLE          1040
#define IDC_BUTTON_CYCLE                1040
#define IDC_BTN_CLOSE_PREVIEW           1040
#define IDC_BTN_LISTEN                  1040
#define IDC_BTN_GET_SECURE_ACCESS       1040
#define IDC_BTN_START_PT_LISTEN         1040
#define IDC_BTN_SET                     1040
#define IDC_BTN_COMMAND                 1040
#define IDC_COMBO_CMD2                  1040
#define IDC_COMBO_TYPE                  1040
#define IDC_BTN_OPEN                    1040
#define IDC_EDIT_UPGRADE_FILENAME       1040
#define IDC_BTN_CLEAR                   1040
#define IDC_COMBO_ALARM_TYPE3           1040
#define IDC_COMBO1_DAY3                 1040
#define IDC_BTN_GET_OSD                 1040
#define IDC_BTN_CANCEL                  1041
#define IDC_BTN_SAVE_CFG                1041
#define IDC_BTN_MANUALIO_STOP           1041
#define IDC_BUTTON_STOP_CYCLE           1041
#define IDC_BTN_STOP_PT_LISTEN          1041
#define IDC_BTN_GET                     1041
#define IDC_COM_PIC_TYPE                1041
#define IDC_BTN_SOUND                   1041
#define IDC_COMBO_ALARM_TYPE4           1041
#define IDC_COMBO1_DAY4                 1041
#define IDC_BTN_SET_OSD                 1041
#define IDC_COMBO_RECORD_TYPE           1041
#define IDC_BTN_SURE                    1042
#define IDC_COMBO_UPLOAD                1042
#define IDC_BTN_SET_HID                 1042
#define IDC_BUTTON_SET                  1042
#define IDC_COMBO_ALARM_TYPE5           1042
#define IDC_COMBO_TIME_TYPE2            1042
#define IDC_COMBO_ALARM_OUT             1043
#define IDC_BTN_GET_HID                 1043
#define IDC_COMBO_STREAM_TYPE           1044
#define IDC_COMBO_EMAIL                 1044
#define IDC_BTN_SET_VIDEO               1044
#define IDC_COMBO1_DAY5                 1044
#define IDC_COMBO_RECORD1               1044
#define IDC_BTN_CYC                     1045
#define IDC_BTN_CIRCLE_PREVIEW          1045
#define IDC_EDIT_ANALOGALARM_NUM        1045
#define IDC_BTN_GET_VIDEO               1045
#define IDC_COMBO1_DAY6                 1045
#define IDC_COMBO_RECORD2               1045
#define IDC_TAB1                        1046
#define IDC_TAB_COMMON_CFG              1046
#define IDC_COMBO_USEPRESET             1046
#define IDC_BTN_SET_PRIVATE             1046
#define IDC_COMBO1_DAY7                 1046
#define IDC_COMBO_RECORD3               1046
#define IDC_COMBO_CURISE                1047
#define IDC_BTN_GET_PRIVATE             1047
#define IDC_COMBO1_DAY8                 1047
#define IDC_COMBO_RECORD4               1047
#define IDC_COMBO_USETRACK              1048
#define IDC_STATIC_PREVIEWBG            1050
#define IDC_BUTTON_ANALOGALARM_OUT      1050
#define IDC_EDIT_ANALOGCHAN_NUM         1051
#define IDC_BUTTON_ANALOGCHAN           1052
#define IDC_EDIT_DIGITALCHAN_NUM        1053
#define IDC_LIST_ALL_LOG                1054
#define IDC_BUTTON_DIGITALCHAN          1054
#define IDC_LIST_ALARM_INFO             1055
#define IDC_BUTTON_ALARMOUT_TIME        1055
#define IDC_BUTTON_ALARMIN_TIME         1056
#define IDC_BTN_OK                      1060
#define IDC_COMBO_WEEKDAY_OUT           1061
#define IDC_COMBO_WEEKDAY_IN            1062
#define IDC_TREE1                       1062
#define IDC_COMBO_OUTPUT_ENABLE         1063
#define IDC_EDIT_DELAYTIME              1065
#define IDC_COMBO_DELAYTIME             1066
#define IDC_EDIT2                       1067
#define IDC_EDIT_CMD                    1067
#define IDC_EDIT_CHANNEL_NAME           1067
#define IDC_EDT_KEEPALIVE_INTERVAL      1067
#define IDC_CHK_LOG_AUTO_DEL            1068
#define IDC_EDIT_STRING1                1068
#define IDC_COMBO_FLOW_TYPE             1069
#define IDC_EDT_TIME_COUNT              1069
#define IDC_EDIT_STRING2                1069
#define IDC_COMBO_FLOW_DATE_START       1070
#define IDC_EDIT_STRING3                1070
#define IDC_COMBO_FLOW_TIME_START       1071
#define IDC_EDIT_STRING4                1071
#define IDC_COMBO_FLOW_DATE_STOP        1072
#define IDC_COMBO_FLOW_TIME_STOP        1073
#define IDC_COMBO_COMPRESSION_TYPE      1074
#define IDC_LIST_FLOW_INFO              1074
#define IDC_BTN_SEARCH__FLOW_INFO       1075
#define IDC_STATIC_FINDING_FLOW_INFO    1076
#define IDC_CHK_SHOW_CHANNEL_NAME       1077
#define IDC_EDIT_POS_CHAN_X             1078
#define IDC_EDIT_POS_CHAN_Y             1079
#define IDC_CHK_SHOW_OSD                1080
#define IDC_EDIT_POS_OSD_X              1081
#define IDC_EDIT_POS_OSD_Y              1082
#define IDC_SLIDER_BRIGHTNESS           1083
#define IDC_COMBO_OSD_ATTRIB            1083
#define IDC_CHK_SHOW_WEEK               1084
#define IDC_BTN_START_PUSH              1085
#define IDC_CHK_SHOW_OSD2               1085
#define IDC_COMBO_PRESET                1086
#define IDC_BTN_STOP_AUDIOTALK          1086
#define IDC_EDIT_POS_OSD_X2             1086
#define IDC_COMBO_SPEED                 1087
#define IDC_IPADDR_STREAM_SERVER        1087
#define IDC_EDIT_POS_OSD_Y2             1087
#define IDC_EDT_ALARM_SERVER_IP         1088
#define IDC_CHK_SHOW_OSD3               1088
#define IDC_EDT_ALARM_SERVER_UDP_PORT   1089
#define IDC_EDIT_POS_OSD_X3             1089
#define IDC_EDT_ALARM_SERVER_TCP_PORT   1090
#define IDC_EDIT_POS_OSD_Y3             1090
#define IDC_BUTTON3                     1091
#define IDC_BTN_REG_CFG_OK              1091
#define IDC_BTN_AUDIOTALK_TEST          1091
#define IDC_CHK_SHOW_OSD4               1091
#define IDC_BTN_STOP_UPGRADE            1091
#define IDC_COM_ALARM_ACCESS_TYPE       1092
#define IDC_EDIT_POS_OSD_X4             1092
#define IDC_COMBO3                      1093
#define IDC_COM_STREAM_ACCESS_TYPE      1093
#define IDC_EDIT_POS_OSD_Y4             1093
#define IDC_COM_LOCAL_TYPE              1094
#define IDC_EDT_PIC_SERVER_IP           1094
#define IDC_CHK_SHOW_OSD5               1094
#define IDC_CHECK1                      1095
#define IDC_CHK_RECORD                  1095
#define IDC_EDT_PIC_SERVER_PORT         1095
#define IDC_CHECK_SENSIVE               1095
#define IDC_CHECK_CAP                   1095
#define IDC_EDIT_POS_OSD_X5             1095
#define IDC_BTN_PRESET_ADJUST           1096
#define IDC_BTN_REG_CFG                 1096
#define IDC_CHECK_VIDEO_LOST            1096
#define IDC_CHECK2                      1096
#define IDC_EDIT_POS_OSD_Y5             1096
#define IDC_BTN_PRESET_DELETE           1097
#define IDC_CHECK_PRIVATE               1097
#define IDC_CHECK3                      1097
#define IDC_BTN_CMS_ALARM               1098
#define IDC_CHECK4                      1098
#define IDC_BTN_PRESET_SETUP            1099
#define IDC_IPADDRESS_TRANSMIT          1099
#define IDC_STATIC_CMD                  1100
#define IDC_UPGRADE_SERVER_IP           1101
#define IDC_COMBO_LOG_MAJOR_TYPE        1102
#define IDC_CHECK_ENABLE1               1102
#define IDC_COMBO_LOG_MINOR_TYPE        1103
#define IDC_BTN_SEARCH_DEV_LOG          1104
#define IDC_COMBO_LOG_DATE_START        1105
#define IDC_COMBO_LOG_TIME_START        1106
#define IDC_STATIC_AREA                 1107
#define IDC_EDIT_INTERAL_WIRELESSINFO_UPLOAD 1107
#define IDC_PROG_UPGRADE                1108
#define IDC_BTN_GET_WIRELESSINFO        1108
#define IDC_CHECK_ENABLE                1108
#define IDC_STATIC_PROGRESS             1109
#define IDC_BTN_SET_WIRELESSINFO        1109
#define IDC_EDIT_MIN22                  1124
#define IDC_EDIT_MIN62                  1125
#define IDC_EDIT_MIN41                  1128
#define IDC_EDIT_MIN81                  1129
#define IDC_SUB_HARDWARE_VERSION        1146
#define IDC_COMBO_RESOLUTION            1146
#define IDC_SUB_SOFTWARE_VERSION        1147
#define IDC_COMBO_FRAME_RATE            1147
#define IDC_SUB_QMB_VERSION             1148
#define IDC_COMBO_IMAGE_QUALITY         1148
#define IDC_SUB_DSP_VERSION             1150
#define IDC_COMBO_BIT_RATE_TYPE         1150
#define IDC_COMBO_MAX_BIT_RATE          1151
#define IDC_COMBO_ALARM_IN_WEEKDAY      1158
#define IDC_EDIT_HOUR31                 1163
#define IDC_EDIT_HOUR71                 1164
#define IDC_EDIT_HOUR41                 1165
#define IDC_EDIT_HOUR81                 1166
#define IDC_RADIO_LOCAL_LOG             1189
#define IDC_EDIT_HOUR11                 1189
#define IDC_RADIO_ALARM_INFO            1190
#define IDC_EDIT_HOUR51                 1190
#define IDC_COMBO_DATE_START            1202
#define IDC_COMBO_TIME_START            1203
#define IDC_COMBO_DATE_STOP             1204
#define IDC_COMBO_TIME_STOP             1205
#define IDC_LIST_REC_FILE               1206
#define IDC_COMBO_DATE_START_PLAY       1207
#define IDC_BTN_SEARCH_REC_FILE         1208
#define IDC_COMBO_DATE_START_PLAY2      1208
#define IDC_COMBO_TIME_START_PLAY       1209
#define IDC_COMBO_DATE_STOP_PLAY        1210
#define IDC_COMBO_TIME_STOP2            1211
#define IDC_COMBO_TIME_STOP_PLAY        1211
#define IDC_COMBO_TIME_START_PLAY2      1212
#define IDC_COMBO_DATE_STOP_PLAY2       1213
#define IDC_COMBO_TIME_STOP_PLAY2       1214
#define IDC_COMBO_DATE_START_PLAY3      1215
#define IDC_COMBO_TIME_START_PLAY3      1216
#define IDC_COMBO_DATE_STOP_PLAY3       1217
#define IDC_COMBO_TIME_STOP_PLAY3       1218
#define IDC_COMBO_DATE_START_PLAY4      1219
#define IDC_COMBO_TIME_START_PLAY4      1220
#define IDC_COMBO_DATE_STOP_PLAY4       1221
#define IDC_COMBO_TIME_STOP_PLAY4       1222
#define IDC_COMBO_REC_FILE_TYPE         1236
#define IDC_STATIC11                    1336
#define IDC_STATIC12                    1338
#define IDC_STATIC13                    1340
#define IDB_BITMAP_PLAYANDREC           1343
#define IDB_BITMAP_ALARM                1344
#define IDB_BITMAP_P_R_A                1346
#define IDB_BITMAP_PLAY                 1347
#define IDB_BITMAP_LOGIN                1348
#define IDB_BITMAP_FORTIFY              1349
#define IDB_BITMAP_FORTIFY_ALARM        1350
#define IDB_BITMAP_DEV_ALARM            1351
#define IDB_BITMAP_CHAN_OFF             1353
#define IDC_EDIT_BIT_RATE               1466
#define IDC_STATIC6                     1501
#define IDC_STATIC7                     1502
#define IDC_STATIC8                     1503
#define IDC_STATIC9                     1504
#define IDC_STATIC10                    1505
#define IDC_STATIC14                    1506
#define IDC_EDIT_HOUR12                 2110
#define IDC_EDIT_HOUR52                 2111
#define IDC_EDIT_MIN11                  2119
#define IDC_EDIT_MIN51                  2120
#define IDC_EDIT_MIN12                  2121
#define IDC_EDIT_MIN21                  2122
#define IDC_EDIT_HOUR22                 2123
#define IDC_EDIT_MIN52                  2124
#define IDC_EDIT_MIN31                  2125
#define IDC_EDIT_HOUR32                 2126
#define IDC_EDIT_MIN32                  2127
#define IDC_EDIT_MIN61                  2128
#define IDC_EDIT_HOUR42                 2129
#define IDC_EDIT_MIN42                  2130
#define IDC_EDIT_HOUR62                 2131
#define IDC_EDIT_MIN71                  2132
#define IDC_EDIT_HOUR72                 2133
#define IDC_EDIT_MIN72                  2134
#define IDC_EDIT_HOUR82                 2135
#define IDC_EDIT_MIN82                  2136
#define IDC_EDIT_HOUR21                 2163
#define IDC_EDIT_HOUR61                 2164
#define ID_32771                        32771
#define ID_3D                           32772
#define ID_MENU_PZIN                    32773
#define ID_MENU_PT                      32774
#define ID_MENU_PTRACK                  32775
#define ID_32776                        32776
#define ID_MENU_XML_CFG                 32777
#define ID_32778                        32778
#define ID_CHANNEL_INFO                 32779
#define ID_32780                        32780
#define ID_MENU_PROXY                   32781
#define ID_32782                        32782
#define ID_GET_GPS_INFO                 32783
#define ID_MENU_GPS_INFO                32784
#define ID_32785                        32785
#define ID_MENU_ISAPI_PT                32786
#define ID_Menu                         32787
#define ID_MENU_UPGRADE                 32788
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_ENABLE_CFG                   32792
#define ID_32793                        32793
#define ID_RECODR_CFG                   32794
#define ID_32795                        32795
#define ID_CAPTURE_PIC                  32796
#define ID_32797                        32797
#define ID_MONTION_AREA                 32798
#define ID_32799                        32799
#define ID_PRIVATE_AREA                 32800
#define ID_32801                        32801
#define ID_HIDE_ALARM                   32802
#define ID_32803                        32803
#define ID_32804                        32804
#define ID_MENU_HTTP_UPGRADE            32805
#define ID_MENU_ISAPI_CFG               32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_MENU_WIRELESS_INFO           32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
